### ISSUE TITLE
Stupid user can't get it to work

### ISSUE THREAD

**Issue by rghvdberg** [ssj71/OSC2MIDI#21]
What am I doing wrong 
Successfully compiled on Linux Mint 17.2 (no extra repos) and Mint 17.1 with kxstudio repos
Android OSC on phone CM 12.1 and tablet Android 4.4

run osc2midi -v -mon on laptop
start Control app . add destination url http://192.168.1.93
add port 57120
select destination
select DJ interface
can't see any OSC messages in the osc2midi terminal

HELP!!! ;-)

**Comment by ssj71** [comment]
Are the phone and computer on the same network? Have you double checked the
IP address matches your computers? It's got to be some kind of connectivity
issue.

**Comment by ssj71** [comment]
you can try to oscsend something to osc2midi from your own computer as a test. Something like:
oscsend localhost 57120  /test/hi ii 14 23

**Comment by rghvdberg** [comment]
oscsend was succesful, had to install liblo-tools first though

**Comment by ssj71** [comment]
thats good. I guess next try
oscsend osc.udp://192.168.1.93:57120 /test/2 f i 2.1 7

**Comment by rghvdberg** [comment]
oscsend osc.udp://192.168.1.93:57120  /test/2 f i 2.1 7
An invalid value was given: 'i'
Failed to create OSC message.
???

**Comment by ssj71** [comment]
oops no space between fi:
oscsend osc.udp://192.168.1.93:57120 /test/2 fi 2.1 7

**Comment by rghvdberg** [comment]
that works
osc2midi -v -mon
Monitor mode, incoming OSC messages will only be printed.
starting osc server on port 57120
Ready.
/test/2 fi, 2.100000, 7

**Comment by ssj71** [comment]
oh, wait, is the computer connected through ethernet? Some access points/routers put wifi and ethernet on different subnets. Can you read the phone's ip address?

**Comment by rghvdberg** [comment]
192.168.1.87 ...
Op 23 nov. 2015 21:04 schreef "ssj71" notifications@github.com:

**Comment by ssj71** [comment]
so its the same sub address. try pinging the phone from the cpu
ping 192.168.1.87

**Comment by ssj71** [comment]
actually, first, did you try entering in the address in control app withouth "http://"?
hit + to enter new destination
URL: 192.168.1.93
port: 57120

**Comment by rghvdberg** [comment]
that was it !
works now!
sorry for wasting your time

**Comment by ssj71** [comment]
naw, I'm sorry for the runaround. I should have noticed that earlier. I'm just glad its working now! go do some cool stuff with it :)
