### ISSUE TITLE
Windows/macOS

### ISSUE THREAD

**Issue by AlexFundorin** [ssj71/OSC2MIDI#25]
No GUI? No love for windows users?

**Comment by ssj71** [comment]
Go ahead and build it for windows, let me know if any build errors occur and I'll fix it. The libraries I use are all cross platform AFAIK. IIRC it has been build and used in OSX.

No gui. IMHO its not really necessary or helpful for this task.

**Comment by AlexFundorin** [comment]
As far as I can see, those mapping only allow direct conversion and no scripting, so this bridge won't suite my needs even if I could build it for Windows. Thanks for your attention.

**Comment by ssj71** [comment]
May I ask what your use case is? What sort of scripting are you interested in?

With Linux you could easily write bash scripts to do most anything with osc2midi, but I really don't know much about Windows. I just don't use it that much. It's quite possible that there's some very practical stuff that I haven't thought about, so I ask. I might be able to add it.

Sorry osc2midi didn't fill your need, but it is a pretty specific tool.

**Comment by AlexFundorin** [comment]
My task is also pretty specific. 
I want to control DAW (Reaper) with MIDI controller via OSC protocol and have LED/LCD feedback on controller. While Reaper can be controlled directly via MIDI, it doesn't support MIDI feedback. At the same time, Reaper can send OSC feedback (type and amount of in/out commands is configurable via ini file). 
So, the point is to always have some configurable middleware converter running between Reaper nad midi controller, so it could convert incoming midi into specific OSC format that is used by Reaper. Then, it should convert OSC commands into LED feedback (simple CC on messages) and LCD feedback (SYSEX messages with cursor position on LCD screen and ASCII to sysex conversion).
While I'm describing you the task, I'm starting to realise that it's far more complicated than your OSC2MIDI app could ever do. 
I think that I'll continue searching for the right tool. :)

**Comment by agraef** [comment]
OSC2MIDI can't do sysex messages IIRC. Osculator can probably do most of what you want, but it's Mac-only. You could give Pd a try and program your own converter, if you are into that. Or, if you can put your controller into a Mackie compatible mode, Reaper might be able to talk to it directly via the appropriate extension (http://forum.cockos.com/showthread.php?t=87265; haven't tried it, though).

**Comment by AlexFundorin** [comment]
I've tried every possible solution for Windows, incuding Pd (awful) and Processing. Will stick to the Ctrlr and wait till the new version will come out, where OSC part should be fixed. Thanks.
