### ISSUE TITLE
osc2midi syntax description

### ISSUE THREAD

**Issue by agraef** [ssj71/OSC2MIDI#26]
Hi Spencer, attached is a Markdown file with documentation of the osc2midi map file syntax and the meaning of the various constructs. The Examples section is still missing, but I guess that it should be useful even as it is, so I'm tossing it here so that you can have a look and decide whether you might add it to the repo. I've had this lying around on my hard disk for much too long, wanting to finish it before submitting, but given that I'm always busy with so many other projects, it's unlikely that I can finish it any time soon. So here goes...
[syntax.md.zip](https://github.com/ssj71/OSC2MIDI/files/701769/syntax.md.zip)

**Comment by agraef** [comment]
For the time being, I've also uploaded the file to the osc2midi-utils wiki, so that it doesn't go to waste. You can find it here: https://bitbucket.org/agraef/osc2midi-utils/wiki/Home

**Comment by ssj71** [comment]
I've looked a little at it, sorry I haven't replied yet. My only thought is that the BNF is a bit intimidating if you aren't familiar with BNF (which I am not). I wonder if we could put that  in a separate, linked file so its not the first thing users are presented with when they look at it? I can do that when I add it here if you think that would be ok.

**Comment by agraef** [comment]
Yeah, that's a good idea, but I'd simply put it in an appendix at the end of the document so that everything is in a single file. Also, the Syntax section then needs some rewording and expanding so that the remarks about the path and argtypes syntax make any sense. I'll rework it asap.

**Comment by ssj71** [comment]
I was looking at this and went ahead and threw it in with some minor edits. Feel free to contribute  PRs for edits as you see fit. Thanks for this!

**Comment by agraef** [comment]
Thanks for taking care of it. Sorry for the high latency, I'm too busy with other projects right now. :)
