### ISSUE TITLE
release more frequently

### ISSUE THREAD

**Issue by dvzrv** [ssj71/OSC2MIDI#31]
It would be great to have releases more frequently. The latest changes seem to fix issues, but have never been released!

I'm about to move this to Arch Linux [community]! :)

**Comment by ssj71** [comment]
if you insist :)
https://github.com/ssj71/OSC2MIDI/releases/tag/v0.2.4

I keep wishing I had more time to improve this, but its really nearly a complete thing not requiring any immediate attention, so it stays on the back burner.

**Comment by dvzrv** [comment]
On 2018-11-20 15:35:44 (-0800), ssj71 wrote:
> if you insist :)
> https://github.com/ssj71/OSC2MIDI/releases/tag/v0.2.4

Thanks a lot!

> I keep wishing I had more time to improve this, but its really nearly
> a complete thing not requiring any immediate attention, so it stays on
> the back burner.

Yeah, time is always problematic... only 24h/day. ;-)
