### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by dvzrv** [ssj71/OSC2MIDI#33]
I just realized this project doesn't provide any licensing information at all.
Can you please add a `LICENSE` or `COPYING` file stating this? Otherwise I'm not able to package it in binary form in the official repositories.

**Comment by ssj71** [comment]
added, it should have had that before. Do you need it to be in the release package or is it ok to just have it in the master branch?

**Comment by dvzrv** [comment]
Thanks for the prompt reply!
It would be very good to have it in a release tarball. Distributions such as Fedora/Debian have licensing teams and will be very picky (they would probably even request a header in each source code file).

**Comment by ssj71** [comment]
ok, if/when they request each file to have a header I'll add it, but for now, theres a new release tarball. Thanks!

**Comment by dvzrv** [comment]
Cool, thanks! Also, you're live now: https://www.archlinux.org/packages/community/x86_64/osc2midi/

**Comment by ftoledo** [comment]
I'm working on Debian Package https://github.com/ftoledo/pkg-osc2midi
