### ISSUE TITLE
Custom JACK MIDI port names?

### ISSUE THREAD

**Issue by jebofponderworthy** [ssj71/OSC2MIDI#35]
Is it possible to set custom JACK MIDI port names?

**Comment by ssj71** [comment]
not ATM. This sounds perhaps like a reasonable feature. I saw your discussion on LAD. 
Is the meta-data solution suggested sufficient? (If it works and I don't have to add a feature, I'd rather keep OSC2MIDI as simple as possible)

**Comment by noedigcode** [comment]
I added custom JACK client name functionality, see https://github.com/noedigcode/OSC2MIDI/tree/AddJackClientName. Might be of use to someone. It's quite a small change, doesn't make the program much more complex in my opinion.

**Comment by ssj71** [comment]
agreed. merged to master. Thanks @noedigcode!
