### ISSUE TITLE
Unable to start when using usb sound card

### ISSUE THREAD

**Issue by raspberryguitar** [ssj71/OSC2MIDI#41]
So im making a raspberry pi digital guitar amp and have a usb audio interface connected to my pi. When i start osc2midi it tries to connect with hw:0 but my soundcard is hw:1 is there a way to fix this?

starting osc server on port 57120
 sending osc messages to address osc.udp://localhost:8000
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
control open "hw:0" (No such file or directory)
control open "hw:0" (No such file or directory)
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
control open "hw:0" (No such file or directory)
ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
ALSA: Cannot open PCM device alsa_pcm for playback. Falling back to capture-only mode
JackTemporaryException : now quits...
control open "hw:0" (No such file or directory)
control open "hw:0" (No such file or directory)
Cannot initialize driver
JackServer::Open failed with -1
Failed to open server
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Could not connect to the JACK server; run jackd first?

Thanks...

**Comment by ssj71** [comment]
Sorry I'm a bit short on time ATM, but are you very familiar with using JACK audio (see jackaudio.org)? OSC2MIDI is built around using JACK for midi (for better or worse). Some googling will probably give a good intro if you are new to using it sorry I didn't find a great one in the 30 seconds I tried. On the PI there may be some hints here: https://www.reddit.com/r/linuxaudio/comments/hiuqxs/jack_sound_server_on_raspberry_pi_with_usb_sound/

**Comment by raspberryguitar** [comment]
Well the soundcard with jack is running... osc2midi just wants to use a different audio channel.

**Comment by ssj71** [comment]
ok, that's odd. I guess it looks like it's not detecting that jack server is running and instead tries to create a new server using hw:0. 

 There is an option if you go to the source in https://github.com/ssj71/OSC2MIDI/blob/master/src/jackmidi.c#L584 you could provide the JackServerName option rather than no options. Something like
`seq->jack_client = jack_client_open(clientname, JackServerName, NULL, "YourJackServerName");`
TBH I don't know how jack servers are named, I usually am on desktop using jackd so if you are more barebones running on a PI I haven't done this myself. Does that help at all?

**Comment by ssj71** [comment]
I'm sorry I wasn't able to find a resolution to this. I'd like to close this issue as I'm not sure if it's affecting people generally and I don't have enough information to provide a fix. Please re-open or create a new one if you'd like.
