### ISSUE TITLE
Piano Roll touchosc and mapping file for 720 x 1280

### ISSUE THREAD

**Issue by Iliolou** [ssj71/OSC2MIDI#42]
Rename Piano.zip to Piano.touchosc and move it to tablet/phone using the java touchosc-editor
Rename Piano.txt to Piano.omm and move it to /usr/share/osc2midi/touchosc/Piano.omm
[Piano.zip](https://github.com/ssj71/OSC2MIDI/files/6826331/Piano.zip)
[Piano.txt](https://github.com/ssj71/OSC2MIDI/files/6826333/Piano.txt)

**Comment by ssj71** [comment]
Thanks for the contribution! Sorry it took me a bit to get to it. I placed it in a subdirectory in the touchosc dir since it had the touchosc file bundled in, seemed to make sense to me.
